### ISSUE TITLE
To do before a release

### ISSUE THREAD

**Issue by samuelcolvin** [datafusion-contrib/datafusion-functions-json#5]
* [x] check docstrings are okay
* [x] create a new release of jiter and use it, currenly we're using `main` - #6
* [x] ~~datafusion needs to make the error shown when you compare to a union less ugly - https://github.com/apache/datafusion/issues/10180~~ - in logfire for this, seems to work well

**Comment by alamb** [comment]
> @alamb would you be able to make a release of `datafusion-functions-json`?
> 
> Alternatively, I'd be happy to use my crates account initially, then transfer the project to you/apache when you're ready?

I think you should feel free to make a release whenever using your crates account. Let's just make sure the documentation makes it clear this is not an official Apache Software Foundation release. 

(BTW I really want to play with this functionality, but I have been swamped with other things, most recently https://github.com/apache/arrow-datafusion/issues/8282. This really looks neat)

**Comment by samuelcolvin** [comment]
okay, I'll make a release but add a prominent message in the readme explaining this is not official.

**Comment by samuelcolvin** [comment]
done - https://crates.io/crates/datafusion-functions-json.

**Comment by alamb** [comment]
Nice!

**Comment by alamb** [comment]
![Screenshot 2024-05-02 at 5 19 54 PM](https://github.com/datafusion-contrib/datafusion-functions-json/assets/490673/15a85912-f18b-4ed9-942a-59765471bd90)
![image](https://github.com/datafusion-contrib/datafusion-functions-json/assets/490673/ce8f4694-8411-4de7-a412-ec0f3af9a202)
